steps:
  - name: "python:3.14"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -ex
        # Устанавливаем gcloud CLI
        pip install --upgrade pip
        pip install google-cloud-sdk

        REGION="us-central1"
        echo "Deploying to region: $REGION"
        gcloud functions deploy my_function \
          --gen2 \
          --region="$REGION" \
          --runtime=python311 \
          --source=. \
          --entry-point=main \
          --trigger-http \
          --allow-unauthenticated
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
