steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:latest"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        REGIONS=("us-central1")

        for REGION in "${REGIONS[@]}"; do
          echo "Deploying to region: $REGION"

          gcloud functions deploy my_function \
            --gen2 \
            --region=$REGION \
            --runtime=python311 \
            --source=. \
            --entry-point=main \
            --trigger-http \
            --allow-unauthenticated
        done

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
