steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:latest"
    entrypoint: 'python3'
    args:
      - "-c"
      - |
        import subprocess

        REGIONS = ["us-central1"]
        
        FUNCTION_NAME = "my_function"
        RUNTIME = "python311"
        ENTRY_POINT = "main"

        for region in REGIONS:
            print(f"Deploying function to region: {region}")
            
            command = [
                'gcloud', 'functions', 'deploy', FUNCTION_NAME,
                '--gen2',
                f'--region={region}',
                f'--runtime={RUNTIME}',
                '--source=.',
                f'--entry-point={ENTRY_POINT}',
                '--trigger-http',
                '--allow-unauthenticated'
            ]
            
            subprocess.run(command, check=True)
            print(f"Successfully deployed to {region}")


timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
