steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'Deploy-Functions-To-Regions'
    entrypoint: 'python'
    args:
      - '-c'
      - |
        import subprocess
        
        REGIONS = ["us-central1"] 
        
        FUNCTION_NAME = "my_function"
        
        for region in REGIONS:
            print(f"Deploying to region: {region}")
            
            command = [
                'gcloud', 'functions', 'deploy', FUNCTION_NAME,
                '--gen2',
                f'--region={region}',
                '--runtime=python311',
                '--source=.',
                '--entry-point=main',
                '--trigger-http',
                '--allow-unauthenticated'
            ]

            subprocess.run(command, check=True)

timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY