steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:latest"
    entrypoint: 'python3'
    args:
      - "-c"
      - |
        import subprocess
        import json

        REGIONS = ["us-central1"]        
        FUNCTION_NAME = "my_function"
        RUNTIME = "python311"
        ENTRY_POINT = "main"
        deployed = []

        for region in REGIONS:
            print(f"Deploying function to region: {region}")
            
            command = [
                'gcloud', 'functions', 'deploy', FUNCTION_NAME,
                '--gen2',
                f'--region={region}',
                f'--runtime={RUNTIME}',
                '--source=infra/proxy_lambda/source/',
                f'--entry-point={ENTRY_POINT}',
                '--trigger-http',
                '--timeout=600s'
            ]
            
            subprocess.run(command, check=True)
            describe_cmd = [
                'gcloud', 'functions', 'describe', FUNCTION_NAME,
                '--region', region,
                '--gen2',
                '--format=json'
            ]
            result = subprocess.run(describe_cmd, check=True, capture_output=True, text=True)
            func_info = json.loads(result.stdout)
            deployed.append(func_info)
            print(f"Successfully deployed to {region}")

        with open('/workspace/functions.json', 'w') as f:
            json.dump(deployed, f)

timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: gs://qa-test-roidev/qa-function-creation/
    paths: ["functions.json"] 
