steps:
  # ---------------------------------------------
  # (0) Build Docker image with Playwright preinstalled
  # ---------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/my_function:latest",
        "infra/proxy_lambda/source"
      ]

  # ---------------------------------------------
  # (1) Пушим Docker-образ в Artifact Registry
  # ---------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/my_function:latest"
      ]

  # ---------------------------------------------
  # (2) Deploy function using custom Docker image
  # ---------------------------------------------
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:latest"
    id: Deploy
    entrypoint: 'python3'
    args:
      - "-c"
      - |
        import subprocess
        import json

        REGIONS = ["us-central1"]        
        FUNCTION_NAME = "my_function"
        DOCKER_IMAGE = "gcr.io/$PROJECT_ID/my_function:latest"
        ENTRY_POINT = "main"
        deployed = []

        for region in REGIONS:
            print(f"Deploying function to region: {region}")
            
            command = [
                'gcloud', 'functions', 'deploy', FUNCTION_NAME,
                '--gen2',
                f'--region={region}',
                f'--image={DOCKER_IMAGE}',
                f'--entry-point={ENTRY_POINT}',
                '--trigger-http',
                '--timeout=600s'
            ]
            
            subprocess.run(command, check=True)
            describe_cmd = [
                'gcloud', 'functions', 'describe', FUNCTION_NAME,
                '--region', region,
                '--gen2',
                '--format=json'
            ]
            result = subprocess.run(describe_cmd, check=True, capture_output=True, text=True)
            func_info = json.loads(result.stdout)
            deployed.append(func_info)
            print(f"Successfully deployed to {region}")

        with open('/workspace/functions.json', 'w') as f:
            json.dump(deployed, f)

timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: gs://qa-test-roidev/qa-function-creation/
    paths: ["functions.json"] 
