steps:
  # ---------------------------------------------
  # (0) Build Docker image with Playwright preinstalled
  # ---------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/my-function:latest",
        "infra/proxy_lambda/source"
      ]

  # ---------------------------------------------
  # (1) Пушим Docker-образ в Artifact Registry
  # ---------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/my-function:latest"
      ]

  # ---------------------------------------------
  # (2) Deploy function using custom Docker image
  # ---------------------------------------------
  - name: "gcr.io/cloud-builders/gcloud"
    id: Deploy
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        gcloud components update --quiet
        python3 infra/proxy_lambda/deploy_function.py

    env:
      - 'PROJECT_ID=$PROJECT_ID'

timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: gs://qa-test-roidev/qa-function-creation/
    paths: ["functions.json"] 
